// components/PostIndex.svelte
<script>
  export let posts;

  let count = 0;

  function handleClick() {
    count = count+1;
  }
</script>
<button on:click={handleClick}>count: {count}</button>
<h1>All posts</h1>
{#each posts as post}
<h2><a href="/post/view/{post.id}">{post.title}</a></h2>
{/each}
<h3><a href="/post/edit/">add post</a></h3>

// components/PostIndex.jsx
import React from "react";

export default class extends React.Component {
  render() {
    const {posts} = this.props;

    return (<>
      <h1>All posts</h1>
      {posts.map(({id, title}) => (
        <h2><a href={`/react/post/view/${id}`}>{title}</a></h2>
      ))}
      <h3><a href="/react/post/edit/">add post</a></h3>
    </>);
  }
}
