// components/PostView.jsx
import React from "react";

export default class extends React.Component {
  render() {
    const {_id, title, text} = this.props.post;
    const {comments} = this.props;

    return (
      <div>
        <h1>{title}</h1>
        <p>{text}</p>
        <a href={`/react/post/edit/${_id}`}>Edit post</a>
        <h2>Comments</h2>
        {comments.map(({text}) => (
          <p>{text}</p>
        ))}
        <a href={`/react/comment/add?post_id=${_id}`}>Add comment</a>
        <form action={`/react/post/delete/${_id}`} method="post">
          <input type="submit" value="Delete post" />
        </form>
      </div>
    )
  }
}

// components/PostView.vue
<template>
<div>
  <h1>{{post.title}}</h1>
  <p>{{post.text}}</p>
  <a :href="`/vue/post/edit/${post._id}`">Edit post</a>
  <h2>Comments</h2>
  <div v-for="comment in comments">
    <p>{{comment.text}}</p>
  </div>
  <a :href="`/vue/comment/add?post_id=${post._id}`">Add comment</a>
  <form :action="`/vue/post/delete/${post._id}`" method="post">
    <input type="submit" value="Delete post" />
  </form>
</div>
</template>
