// components/frontend/react/PostIndex.jsx
import Head from "@primate/frontend/react/head";
import t from "@primate/i18n/react";
import locale from "@primate/i18n/react/locale";
import { useState } from "react";
import PostLink from "./PostLink.jsx";

export default ({ posts, title, request }) => {
  const [count, setCount] = useState(0);
  return <>
    <Head>
      <title>Primate template app (React)</title>
      <meta name="keywords" content={title} />
    </Head>
    <h1 onClick={() => { console.log("clicked!"); }}>{t("All posts")}</h1>
    {posts.map(post => <PostLink post={post} />)}
    <h3>{t("Counter")}</h3>
    <div>{count}</div>
    <button onClick={(() => setCount(count => count + 1))}>+</button>
    <h3>{t("Switch language")}</h3>
    <div><a onClick={() => locale.set("en-US")}>{t("English")}</a></div>
    <div><a onClick={() => locale.set("de-DE")}>{t("German")}</a></div>
  </>;
}

// components/frontend/svelte/PostIndex.svelte
<script>
  import t from "@primate/svelte/i18n";
  import locale from "@primate/svelte/locale";
  import PostLink from "./PostLink.svelte";

  export let posts = [], title = "";
  let count = 0;
</script>
<svelte:head>
  <title>Primate template app (Svelte)</title>
  <meta name="keywords" content={title} />
</svelte:head>
<h1 on:click={() => { console.log("clicked!"); }}>{$t("All posts")}</h1>
{#each posts as post}
<PostLink {post} />
{/each}
<h3>{$t("Counter")}</h3>
<div>
<button on:click={() => { count = count - 1; }}>-</button>
<button on:click={() => { count = count + 1; }}>+</button>
{count}
</div>
<h3>{$t("Switch language")}</h3>
<div><a on:click={() => locale.set("en-US")}>{$t("English")}</a></div>
<div><a on:click={() => locale.set("de-DE")}>{$t("German")}</a></div>
